services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./src/database:/docker-entrypoint-initdb.d
    command: -p 5432
